version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  shared_static: {}
  media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: chitweb_production_django
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - shared_static:/app/staticfiles
      - media:/app/chitweb/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: chitweb_production_postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: chitweb_production_nginx
    depends_on:
      - django
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 65535
    volumes:
      - shared_static:/usr/share/nginx/html/static
      - ./log:/var/log/nginx
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:5.0
    restart: always

