# Generated by Django 2.2.9 on 2020-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=120, verbose_name='Фамилия')),
                ('short_bio', models.CharField(default='', max_length=200, verbose_name='Описание')),
                ('long_bio', models.TextField(blank=True, default='', verbose_name='Полное описание')),
                ('telegram', models.CharField(default='', max_length=120, verbose_name='Telegram')),
                ('github', models.CharField(blank=True, default='', max_length=120, verbose_name='Github')),
                ('photo', models.ImageField(default='default-profile.png', upload_to='profile-pics', verbose_name='Фото')),
                ('specializations', models.ManyToManyField(to='specialists.Specialization', verbose_name='Специализации')),
            ],
        ),
    ]
