# Generated by Django 3.0.4 on 2020-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile-pics', verbose_name='Фото'),
        ),
    ]
